# Mod
mod_id = waystones
mod_name = Waystones
mod_main=Waystones
description=Teleport back to activated waystones. For Survival, Adventure or Servers.
version = 21.1.44
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/minecraft/waystones
sources=https://github.com/TwelveIterations/Waystones
issues=https://github.com/TwelveIterations/Waystones/issues
license=All Rights Reserved

# Publishing
curseforge_release_type = release
curseforge_project_id = 245755
curseforge_environments = Client,Server
modrinth_release_type = release
modrinth_project_id = LOpKHB2A
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Journeymap
journeymap_project_id=32274
journeymap_forge_file_id=6689204
journeymap_neoforge_file_id=6689206
journeymap_fabric_file_id=6689205
journeymap_api_version=2.0.0-1.21.1-SNAPSHOT
journeymap_networking_version=1.0.11-1.21

# Minecraft
minecraft_version = 1.21.1
minimum_minecraft_version = 1.21
minecraft_versions = 1.21.1
minecraft_version_range = [1.21,)
pack_format_number = 18
java_version = 21

# Balm
balm_version = 21.0.59+1.21.1
balm_version_range = [21.0.39,)

# Forge
forge_version = 52.0.2
forge_version_range = [51,)
forge_loader_version_range = [51,)

# NeoForge
neoforge_version = 21.1.8
neoforge_version_range = [21-beta,)
neoforge_loader_version_range = [1,)

# Fabric
fabric_version = 0.116.7+1.21.1
fabric_loader_version = 0.17.3

# Dependencies
jei_minecraft_version=1.21
jei_version=19.0.0.5
rei_version=10.0.581
wthit_version=6.1.1
jade_fabric_version=5427840
jade_neoforge_version=5444008
mixin_version=0.8.5
modmenu_version=8.0.0
theoneprobe_version=4159743
bluemap_version=v2.5.1
dynmap_version=3.7-beta-6
unbreakables_version=21.1.6+1.21.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_author = BlayTheNinth
credits = BlayTheNinth
kuma_version = [21.0,21.2)
neo_form_version = 1.21.1-20240808.144430

include_fabric=true
include_neoforge=true
include_forge=true
