# Mod
mod_id = waystones
mod_name = Waystones
mod_author = BlayTheNinth
credits = BlayTheNinth
description=Teleport back to activated waystones. For Survival, Adventure or Servers.
version = 26.3.0.0
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/mc/waystones
sources=https://github.com/TwelveIterations/Waystones
issues=https://github.com/TwelveIterations/Waystones/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id = 245755
curseforge_environments = Client,Server
modrinth_project_id = LOpKHB2A
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 25
neoforge_snapshot_url =
include_fabric=true
include_neoforge=false
include_forge=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configureondemand=true
