# Mod
version = 14.1.21
mod_id = waystones
group = net.blay09.mods

# Publishing
release_type = release
curseforge_project_id = 245755
modrinth_project_id = LOpKHB2A
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Journeymap v5.8.3
journeymap_project_id=32274
journeymap_forge_file_id=4385902
journeymap_fabric_file_id=4385898
journeymap_api_fabric_version=1.18.2-1.8-fabric-SNAPSHOT
journeymap_api_common_version=1.18.1-1.8-SNAPSHOT
journeymap_api_forge_version=1.18.1-1.8-SNAPSHOT

# Minecraft
minecraft_version = 1.20.1
minecraft_versions = 1.20,1.20.1
minecraft_version_range=[1.20,1.21)
java_version = 17

# Balm
balm_version = 7.3.38+1.20.1
balm_version_range = [7.3.28,)

# Forge
forge_version = 47.3.27
forge_version_range=[46.0.0,)
forge_loader_version_range=[46,)
forge_mixins=true

# Fabric
fabric_version = 0.92.3+1.20.1
fabric_loader_version = 0.16.10

# Dependencies
jei_minecraft_version=1.19.2
jei_version=11.4.0.288
rei_version=10.0.581
wthit_version=6.1.1
jade_fabric_version=4160727
jade_forge_version=4159759
mixin_version=0.8.5
modmenu_version=7.2.2
theoneprobe_version=4159743
cloth_config_version=10.0.95
unbreakables_version=20.1.3-SNAPSHOT

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

include_forge=true
include_fabric=true