name: Report a Bug
description: The game crashed or something is not working as expected.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Filling out this information and providing logs will help get the issue resolved faster.
  - type: dropdown
    id: minecraftVersion
    attributes:
      label: Minecraft Version
      description: What version of Minecraft were you running?
      options:
        - 1.18.x
        - 1.17.x
        - 1.16.x
        - 1.12.x
        - Other (specify below)
    validations:
      required: true
  - type: dropdown
    id: modLoader
    attributes:
      label: Mod Loader
      description: What mod loader were you using?
      options:
        - Forge
        - Fabric
        - SpongeForge
    validations:
      required: true
  - type: input
    id: modLoaderVersion
    attributes:
      label: Mod Loader Version
      description: What version of Forge / Fabric were you using?
    validations:
      required: true
  - type: input
    id: modVersion
    attributes:
      label: Mod Version
      description: What version of the mod were you using?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Be as thorough as possible and provide a step-by-step guide to reproduce the issue.
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: Provide a link to the logs here. You can use a site like pastebin or gist to upload the latest.log content. Make sure they are set to not expire.
  - type: input
    id: optifine
    attributes:
      label: Do you use any performance-enhancing mods (e.g. OptiFine)?
      description: Specify which and test whether the issue happens with those mods disabled.
