# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build-fabric
on: [push]

defaults:
  run:
    working-directory: ./fabric

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            16    # Minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        #os: [ubuntu-20.04, windows-latest]
        os: [ubuntu-20.04] # speed it up for now by only testing one
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build
        env:
          GPR_USERNAME: ${{secrets.GPR_USERNAME}}
          GPR_TOKEN: ${{secrets.GPR_TOKEN}}
          GPR_BUILD_NUMBER: ${{github.run_number}}
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '16' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew publish
        env:
          GPR_USERNAME: ${{secrets.GPR_USERNAME}}
          GPR_TOKEN: ${{secrets.GPR_TOKEN}}
          GPR_BUILD_NUMBER: ${{github.run_number}}